.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.42.2 */

nonmatching D_8008ABC0

dlabel D_8008ABC0
    /* 7B3C0 8008ABC0 00000000 */ .word 0x00000000
    /* 7B3C4 8008ABC4 00000000 */ .word 0x00000000
enddlabel D_8008ABC0

nonmatching D_8008ABC8

dlabel D_8008ABC8
    /* 7B3C8 8008ABC8 00000000 */ .word 0x00000000
    /* 7B3CC 8008ABCC E8030000 */ .word 0x000003E8
enddlabel D_8008ABC8

nonmatching D_8008ABD0

dlabel D_8008ABD0
    /* 7B3D0 8008ABD0 00000000 */ .word 0x00000000
    /* 7B3D4 8008ABD4 00000000 */ .word 0x00000000
enddlabel D_8008ABD0

nonmatching D_8008ABD8

dlabel D_8008ABD8
    /* 7B3D8 8008ABD8 18FC0000 */ .word 0x0000FC18
    /* 7B3DC 8008ABDC 20030000 */ .word 0x00000320
enddlabel D_8008ABD8

nonmatching D_8008ABE0

dlabel D_8008ABE0
    /* 7B3E0 8008ABE0 4A303100 */ .word 0x0031304A
enddlabel D_8008ABE0

nonmatching D_8008ABE4

dlabel D_8008ABE4
    /* 7B3E4 8008ABE4 01000000 */ .word 0x00000001
enddlabel D_8008ABE4

nonmatching D_8008ABE8

dlabel D_8008ABE8
    /* 7B3E8 8008ABE8 01030C0E */ .word 0x0E0C0301
    /* 7B3EC 8008ABEC 00000000 */ .word 0x00000000
enddlabel D_8008ABE8

nonmatching D_8008ABF0

dlabel D_8008ABF0
    /* 7B3F0 8008ABF0 B4000100 */ .word 0x000100B4
enddlabel D_8008ABF0

nonmatching D_8008ABF4

dlabel D_8008ABF4
    /* 7B3F4 8008ABF4 00000000 */ .word 0x00000000
enddlabel D_8008ABF4
