.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* All functions in this file have been decompiled to C (src/lsdde/4CD08.c) */

/* Both the named function SetTeleportsEnabled and all func_8005Cxxx functions */
/* are defined in the C source. See also class_39e08.s for callers. */
